### ISSUE TITLE
Fails with "cargo install ttyper"!

### ISSUE THREAD

**Issue by sallyhaj** [max-niederman/ttyper#106]
Hello there, 
Today, I have try to install ttyper with the command:
`cargo install ttype`
It takes sometimes, but it fails at the end with this message:

> Caused by:
>   package `toml_edit v0.19.15` cannot be built because it requires rustc 1.66.0 or newer, while the currently active rustc version is 1.63.0
>   Try re-running cargo install with `--locked`

It seems that, there is some conflict between versions in rustc, any hint to overcome that?
Thank you.

**Comment by DeflateAwning** [comment]
According to that error message, you need to update your cargo version. Maybe there's another fix, but upgrading cargo is the easiest.

**Comment by sallyhaj** [comment]
Yes, you are right @DeflateAwning , I was using the official debian package, which is a little old, then I install the the new one from the program official website, and it works perfectly.
Thank you.
