### ISSUE TITLE
[Feature request] Option to read text data for typing from file or stdin

### ISSUE THREAD

**Issue by toolleeo** [max-niederman/ttyper#116]
Instead of randomly generating the sequence of words from a list of words, this request asks the possibility to provide the text to type from external source WITHOUT the randomly selection the words.

This would allow to use the interface of ttyper with external "exercises" that can be planned outside the program.

**Comment by max-niederman** [comment]
This is already a feature. Just run `ttyper some_file.txt` and it'll split it at newlines. Note that for reading from stdin, it doesn't support streaming so the file will have to end for the test to start.
