### ISSUE TITLE
[Feature Request] Import quotes or paragraph from json file or standard output.

### ISSUE THREAD

**Issue by amalgame21** [max-niederman/ttyper#122]
Like the project in https://github.com/lemnos/tt
Default quote can be imported by `tt -quotes en`, (imported from file)
Also it can fetch quotes by 

```
              curl https://api.quotable.io/quotes|\
                  jq '[.results[]|.text=.content|.attribution=.author][:2]'|\
                  tt -quotes - -norreport -csv`
```
 (imported from stdout)
That means we can custom make any quote in json as we wish.

**Comment by max-niederman** [comment]
So, ttyper doesn't have a special UI for displaying attributed quotes, but you can import any test from standard input. For example,
```bash
curl https://quotes-api-self.vercel.app/quote | jq -r ".quote" | ttyper -
```

I'm considering adding a special UI in v2, but I don't think it's worth the added complexity for v1.
