### ISSUE TITLE
Cargo Installation Errors? 

### ISSUE THREAD

**Issue by JaedenRotondo** [max-niederman/ttyper#13]
I downloaded the zip file as well as cargo. However, when I run `cargo install ttyper` I get an error saying `link.exe` was not found: 

   Compiling cassowary v0.3.0
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: could not compile `getrandom`

_Apologies if this is an error on my end, I have no prior experience with cargo_

**Comment by max-niederman** [comment]
Cargo build the application from source when you install it, so you need to have Rust's build dependencies installed. Specifically, you need to provide msvc by installing Visual Studio with the Visual C++ option as the error message suggests.
