### ISSUE TITLE
Pressing escape at start crashes the app

### ISSUE THREAD

**Issue by DidiBear** [max-niederman/ttyper#14]
Step to reproduce:
- Starts the app with `ttyper` 
- Press `Escape`
- The app crashes with the error: `The test was completed without any events`

This is caused by [this `expect` line here in `results.rs`](https://github.com/max-niederman/ttyper/blob/main/src/test/results.rs#L99). This can be fixed by setting the `cps` to the default value when there is no event.

**Comment by max-niederman** [comment]
FIxed with v0.1.12 (3a265bb95a336e02254b93c20cafc4ba17c9c7f4).
