### ISSUE TITLE
Starting with --words 0 crashes the app

### ISSUE THREAD

**Issue by DidiBear** [max-niederman/ttyper#15]
Step to reproduce:
- Start the app with `ttype -w 0`
- The app crashes with the error: `index out of bounds: the len is 0 but the index is 0`

This is because the list of `words` is empty but the `current_word` focus to the first element.

One possible solution is to manually parse the argument using `FromStr` [as describe here in `structopt` doc](https://docs.rs/structopt/0.3.21/structopt/#type-magic).\
For example, we can [`clamp`](https://doc.rust-lang.org/stable/std/cmp/trait.Ord.html#method.clamp) the value between 1 and 1000 using [a `newtype` struct](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) (here named `NbWord`):

```rust
/// Number of words, between 1 and 1000.
#[derive(Debug)]
struct NbWord(usize);

impl FromStr for NbWord {
    type Err = ParseIntError;

    fn from_str(text: &str) -> Result<Self, Self::Err> {
        let num = text.parse::<usize>()?;
        Ok(Self(num.clamp(1, 1000)))
    }
}

struct Opt {
    #[structopt(short, long, default_value = "50")]
    words: NbWord,

    // ...
}

impl Opt {
    fn gen_contents(&self) -> Vec<String> {
        // ...

        let mut words: Vec<String> = 
            language.into_iter().cycle().take(self.words.0).collect();
        //                                               ^ note the tuple access here
        
        /// ...  
    }
}

**Comment by max-niederman** [comment]
FIxed with v0.1.12 (3a265bb95a336e02254b93c20cafc4ba17c9c7f4).
