### ISSUE TITLE
[ Request ] Programming language support

### ISSUE THREAD

**Issue by reaganmcf** [max-niederman/ttyper#21]
I use [monkeytype](https://monkeytype.com) very often and one of the best features in my opinion is being able to do typing tests with keywords / syntax of popular programming languages.

If #20 gets approved, then we could even have a list of popular code snippets for that coding language to use as for multi line "quote" coding tests.

**Comment by max-niederman** [comment]
I've added all of monkeytype's coding languages, they'll be available at the next release.
