### ISSUE TITLE
wpm value is not correct 

### ISSUE THREAD

**Issue by Ashutosh-Tripathy** [max-niederman/ttyper#22]
I am getting very high word/minute in the tool. Usually I type 45-65 wpm, but in ttyper sometimes it is showing >100wpm.

I typed the same string in ttyper and typeracer, and the result is very different (as expected getting very high wpm in ttyper)

![image](https://user-images.githubusercontent.com/12702948/117864556-9180eb00-b2b2-11eb-9120-d4d132746a0d.png)
![image](https://user-images.githubusercontent.com/12702948/117864685-b6755e00-b2b2-11eb-84c7-cdcabdaf8049.png)

ttyper 0.2.0

**Comment by max-niederman** [comment]
This is fixed as of [v0.2.2](https://github.com/max-niederman/ttyper/releases/tag/v0.2.2).
