### ISSUE TITLE
thread 'main' panicked at 'Error reading language file.

### ISSUE THREAD

**Issue by dr460nf1r3** [max-niederman/ttyper#25]
Hey, Im getting the following error since the latest update upon launching ttyper: 

```
thread 'main' panicked at 'Error reading language file. Make sure Luthien's config dir isn't missing.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:59:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The used installation method was this [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttyper-git) I created.

**Comment by max-niederman** [comment]
Currently, we only check for the config directory at `$XDG_CONFIG_DIR/ttyper` and `$HOME/.config/ttyper`, so an installation won't work if it's installed by another user. The way to solve this would probably be to detect root installations and install the config to `/etc/ttyper` or similar. What are your thoughts on this?

**Comment by max-niederman** [comment]
It would also be possible to embed the runtime resources into the binary itself using something like [`rust-embed`](https://github.com/pyros2097/rust-embed). That's probably the best solution, as no installation script is necessary whatsoever.

**Comment by dr460nf1r3** [comment]
Sounds great to me 👍🏻

**Comment by max-niederman** [comment]
This should no longer be a problem as of v0.2.3.
