### ISSUE TITLE
Add keywise WPM and accuracy data to the results

### ISSUE THREAD

**Issue by max-niederman** [max-niederman/ttyper#3]
We would likely only show some of the worst keys so that users can know what to work on without getting a useless dump of information.

This shouldn't be difficult to implement as the actual data is already present in the `Results` struct.

**Comment by reaganmcf** [comment]
I would like to work on this 😄

**Comment by reaganmcf** [comment]
I have this solution right now but it's a little hacky in my opinion. Storing the keys as `[Fraction; 256]` makes it really annoying to get the data, particularly sorting to get the worst keys. I feel like rewriting to use a HashMap<char, Fraction> would be much cleaner and more extendible. @max-niederman What do you think?

```rust
// get top 5 worst keys
let mut worst_key_display_str = String::from("Worst Keys:");
let mut key_and_cps_list: Vec<(char, f64)> = Vec::new();
for i in 0..256 {
    let temp = self.cps.per_key[i];
    let ascii_char = i as u8 as char;
    if temp.is_nan() || ascii_char == AsciiChar::BackSpace {
        continue;
    }
    key_and_cps_list.push((ascii_char, temp));
}
key_and_cps_list.sort_by(|a, b| {
    let f1 = a.1;
    let f2 = b.1;
    f1.partial_cmp(&f2).unwrap()
});
for key_and_cps_pair in key_and_cps_list[0..std::cmp::min(key_and_cps_list.len(), 5)].iter()
{
    worst_key_display_str = format!(
        "{}\n- '{}' at {:.2} cps",
        worst_key_display_str, key_and_cps_pair.0, key_and_cps_pair.1
    );
}
info_text.extend(Text::from(worst_key_display_str))
```

Below is an example of the output. I'm not really feeling this implementation with `cps`, and I'm going to use `accuracy` instead.
![](https://i.gyazo.com/b22c225ff42bf86217f18774a1751ebf.png)

**Comment by max-niederman** [comment]
> Storing the keys as `[Fraction; 256]` makes it really annoying to get the data, particularly sorting to get the worst keys. I feel like rewriting to use a HashMap<char, Fraction> would be much cleaner and more extendible.
Yeah, it would probably be a good idea to rewrite the results to use a `HashMap<char, T>` not only for this feature, but also to better support unicode.

**Comment by max-niederman** [comment]
Actually, now I think about it, we could just use a `HashMap<KeyEvent, T>`. @reaganmcf I'm going to work on switching to HashMap for the Results code.

**Comment by reaganmcf** [comment]
@max-niederman Awesome, let me know when you merge it into master and then I'll my PR 👍🏻

**Comment by max-niederman** [comment]
@reaganmcf I've merged the changes with `master`

**Comment by codelixir** [comment]
Hey! I am not getting the worst keys. (Let me know if I should open a separate issue for this)

I am using `ttyper 0.3.1` which is the latest version and I installed it just a few hours ago. The machine is an M1 MacBook.

Here is a screenshot of the results page:
<img width="1485" alt="Screenshot 2021-12-17 at 12 15 49 AM" src="https://user-images.githubusercontent.com/54016648/146430884-69cdce94-fbcf-4cd8-b9f5-309edd17538f.png">

Lmk if I should share anything else
