### ISSUE TITLE
Add ability to restart the test without quitting the program

### ISSUE THREAD

**Issue by MagnumDingusEdu** [max-niederman/ttyper#34]
When testing, I often go off to a bad start and want to restart the test. Currently, I have to quit `ttyper` with <kbd>Ctrl+C</kbd> and then again start it.
It'll be great if there was a shortcut like <kbd>Ctrl+R</kbd> to restart the test (just like refreshing the page in online browser-based tests)

**Comment by khanghugo** [comment]
See [pull #37](https://github.com/max-niederman/ttyper/pull/37) if you are interested

**Comment by max-niederman** [comment]
You can actually already do this by aborting the current test by pressing <kbd>Esc</kbd> and then starting a new test with <kbd>r</kbd>.

**Comment by MagnumDingusEdu** [comment]
Oh, I missed that keybind. Closing this issue,  thanks!

**Comment by max-niederman** [comment]
No problem. I do think it's at least worth consideration to document the binding somehow because it's not necessarily intuitive.

**Comment by MagnumDingusEdu** [comment]
Yeah, fair point.
