### ISSUE TITLE
[bug] "Worst Keys" not shown on results screen

### ISSUE THREAD

**Issue by codelixir** [max-niederman/ttyper#40]
I am using version 0.3.1, I installed ttyper just a few hours ago, and I can't see worst keys on the results screen.

Here is a screenshot:
<img width="1485" alt="Screenshot 2021-12-17 at 12 15 49 AM" src="https://user-images.githubusercontent.com/54016648/146432769-056974ea-d688-482b-b673-a0f68a3cf58f.png">

Since this literally has 0% accuracy, there is no reason to not have worst keys. Even in all of my previous runs with different accuracies (varying between 80%-96%), I haven't seen anything against the worst keys column.

Please let me know if you need me to share any system information or something. Thanks.

**Comment by reaganmcf** [comment]
Is this an issue with the height of the terminal window? Do you get the same behavior if you increase the height a bit?

I'm not near a computer right now but I'm curious if it's just clipping the results

**Comment by codelixir** [comment]
Ah yes, that's it. I can see it when I run the program in full screen.
<img width="1440" alt="Screenshot 2021-12-18 at 4 22 32 PM" src="https://user-images.githubusercontent.com/54016648/146638427-ddc69f2a-14f8-4fcb-b9c0-733eee8fcdb5.png">

Silly me. Closing the issue.
Thanks for the response.

**Comment by max-niederman** [comment]
In the future, it might be worth consideration to put the worst keys in a separate frame so this kind of thing doesn't happen.

**Comment by codelixir** [comment]
so should I reopen (and rename?) this issue?

**Comment by max-niederman** [comment]
> so should I reopen (and rename?) this issue?

No need, it's fixed in `v0.4.0`.
