### ISSUE TITLE
error[E0277]: `[Spans<'_>; 4]` is not an iterator

### ISSUE THREAD

**Issue by grasshopper007** [max-niederman/ttyper#45]
I am running Parrotsec OS
`Distributor ID:	Debian
Description:	Parrot OS 5.0 (LTS)
Release:	5.0
Codename:	bullseye
`
I tried to install ttyper. 
Cargo was already installed
`cargo --version
cargo 1.46.0
`
I got the following error after running 
`cargo install ttyper`
`error[E0277]: `[Spans<'_>; 4]` is not an iterator`
Details to the error are in the attached file. 
![ttyper_error](https://user-images.githubusercontent.com/100096857/154865431-715c5407-dba0-4fe0-b3b3-7ff64c87f308.png)

**Comment by max-niederman** [comment]
This is probably due to the fact that old versions of Rust did not implement `IntoIterator` on arrays due to the lack of const generics. You can fix this by using a more recent Rust version.
