### ISSUE TITLE
Hidden characters with actual code file

### ISSUE THREAD

**Issue by jaron-l** [max-niederman/ttyper#47]
I wanted to practice typing on some coding examples so I decided to give as input an actual code file I had recently written; however, I found that multiple carriage returns in a file produces some unexpected results when trying to type out the file. Here is an example file that shows the results I am seeing:
[main_test.txt](https://github.com/max-niederman/ttyper/files/8404742/main_test.txt)

For reference, here is it typed out:
```c
#include "gtest/gtest.h"
#include "gmock/gmock.h"

class HumTest : public testing::Test {
    
    protected:
        void SetUp() override {
       }

;

TEST_F(HumTest, TestHumQuery)
{
	EXPECT_EQ(1,1);
}
```

When passing this to ttyper, it becomes difficult to get past the includes and on to the class definition. It doesn't present this as a new line. I've tried typing in enters, tabs, and spaces but all seem ignored. What did work was typing some random text and then hitting in enter to register the need to go to the next line.

This presented the problem of dealing with the "protected" line though. On that line, spaces are ignored (I assume because they are registered as a new word command or something), so you have to type in a bunch of random characters to get to the "protected" word, but it still registers as being wrong.

Are the only separators supported by ttyper are new lines and spaces? Perhaps blank lines and tabs could be supported, or parsed out?

**Comment by max-niederman** [comment]
These bugs should be fixed with v0.4.2 and it is possible to use the example you provided; however, ttyper is not really intended for use in files with whitespace like this. I would personally recommend using some kind of text processing to strip the whitespace and likely separate each line into smaller words for the best experience.
