### ISSUE TITLE
[Feature Request] Add word frequency lists

### ISSUE THREAD

**Issue by GrimPixel** [max-niederman/ttyper#52]
There is a guy who gathered the lists:
https://github.com/frekwencja/most-common-words-multilingual

**Comment by GrimPixel** [comment]
Looks like the data is not released for free. Now I doubt if that is legal.

**Comment by GrimPixel** [comment]
I saw the page. They allow the redistribution of their free data.
https://www.wordfrequency.info/samples.asp

**Comment by max-niederman** [comment]
This is a considered feature for v1.0.

**Comment by max-niederman** [comment]
Duplicate of #2.
