### ISSUE TITLE
Don't randomize text to have real life situation

### ISSUE THREAD

**Issue by therealmaxmoon** [max-niederman/ttyper#59]
I really would like to use a real life text, like a blog article to have real sentences under real circumstances. But if I copy a text to a text file, ttyper randomizes every new line in the file.

The reason to have real life text is that it would be much more realistic to learn real sentences and another nice thing to do are competitions, because if there is the same text, the conditions are the same for all.

**Comment by max-niederman** [comment]
Input files aren't randomized. Are you perhaps using the `--language-file` option?

**Comment by therealmaxmoon** [comment]
Yes, I thought this was the way to use a specific text file with ttyper. 

What is the proper way to use a specific text file with ttyper?

**Comment by max-niederman** [comment]
Just pass the input file as the first argument.
