### ISSUE TITLE
Add Cargo-less installation methods

### ISSUE THREAD

**Issue by max-niederman** [max-niederman/ttyper#7]
Ideally there should be a way to install on at least some machines without `cargo`. This will need an installation script to install the language files in lieu of `build.rs`.

Some alternative installation methods which would be good to include are:
- `sh` installation script w/ prebuilt binaries
- AUR package

For prebuilt binaries, it would be ideal to setup GitHub workflows or similar so that no manual work is needed.

**Comment by reaganmcf** [comment]
I currently implemented this for my buddy and I's program called [lightmon](https://github.com/reaganmcf/lightmon). I used the popular shell program `starship` as a reference, and how their installation method works is they have a GitHub Action that generates the binaries for all types of platforms automatically whenever you tag a commit, and attaches them to the corresponding GitHub release page. Then, their shell script will just fetch the corresponding binary based on the platform from the release page and install it. Definitely a very clean way to do it, and not hard to do.

**Comment by dr460nf1r3** [comment]
There is a `ttyper-git` package at AUR maintained by me, currently not working because of #25.

**Comment by max-niederman** [comment]
This is now mostly solved, as pre-built binaries now work out of the box, and binaries are built and uploaded automatically to GitHub releases on every update.

**Comment by BachoSeven** [comment]
perhaps as binaries are built with Releases, a `ttyper-bin` package could also be added to the AUR which ships the latest binary release? That seems to be common with many Rust cli utilities on the aur

**Comment by max-niederman** [comment]
> perhaps as binaries are built with Releases, a `ttyper-bin` package could also be added to the AUR which ships the latest binary release? That seems to be common with many Rust cli utilities on the aur

That would be ideal, but I neither use nor have any experience packaging for Arch, so someone else will probably need to maintain the package.

If anyone's interested in maintaining a package (for _any_ distribution), I'd be happy to integrate it with the existing CI.
