### ISSUE TITLE
words are not randomized from whole file?

### ISSUE THREAD

**Issue by alirezaalavi87** [max-niederman/ttyper#71]
Hi, and thanks for the great app.

It seems to me that words are not randomized from the whole input file. meaning, for example when I use to command:
`ttyper -l english200 -w 10`
the output will be always the words:
the of and to in for is on that by

only in randomized order.
the expected behavior is the command above, returns 10 random words from the whole input file not just the first 10 lines of the file.

**Comment by max-niederman** [comment]
Are you sure you're on the latest version of ttyper? As far as I'm aware, this was fixed in v1.0.0.

**Comment by alirezaalavi87** [comment]
> Are you sure you're on the latest version of ttyper? As far as I'm aware, this was fixed in v1.0.0.

Oh yes you are correct I'm sorry.
Thanks
