### ISSUE TITLE
panic attempt to divide by zero

### ISSUE THREAD

**Issue by GiveMeFox** [max-niederman/ttyper#80]
command:
ttyper -w 1

![2023-05-17_11-48](https://github.com/max-niederman/ttyper/assets/74460065/10d84b43-368b-4a3f-b7b3-66fe90ed2717)
![2023-05-17_11-57](https://github.com/max-niederman/ttyper/assets/74460065/36832b5d-3bb8-4394-93a1-bf46188a195d)

command:
ttyper -w 2

![2023-05-17_11-59](https://github.com/max-niederman/ttyper/assets/74460065/eddbc4bc-a812-4fb1-b302-73fcbdc6d1f1)

**Comment by max-niederman** [comment]
Duplicate of #42.
