### ISSUE TITLE
[Bug] cargo install failed linked `cc` not found

### ISSUE THREAD

**Issue by yoguut** [max-niederman/ttyper#81]
[System]
OS: Fedora 38 Workstation
DE: Gnome

[What happened]
1. Run `cargo install ttyper`
2. Unable to update ttyper due to error `linker cc not found`

**Comment by max-niederman** [comment]
Are you able to install other cargo packages?

**Comment by yoguut** [comment]
> Are you able to install other cargo packages?

yes, I have other tools like `mdbook`

**Comment by yoguut** [comment]
Tried updating other crates, they all failed with exactly the same error. So I believe this is a problem of my own system, not an issue for `ttyper`. Thanks OP. Closing issue now.
