### ISSUE TITLE
As of `1.2.1` all my keystrokes have doubled outputs

### ISSUE THREAD

**Issue by brian6932** [max-niederman/ttyper#85]
This bug basically makes this program unusable for me, `1.2.0` does not exhibit this issue
https://github.com/max-niederman/ttyper/compare/v1.2.0...v1.2.1
OS: Windows 11 22621
Shell: pwsh 7.4.0-preview.3
Term: Alacritty 0.13.0-dev

**Comment by max-niederman** [comment]
Hmm... that's very weird. If you can, I'd recommend rolling back to 1.2.0 until I can figure out why that would happen.

**Comment by brian6932** [comment]
Yea I have rolled back

**Comment by max-niederman** [comment]
It appears that the event loop was treating key presses and key releases identically, so it was duplicating inputs on terminals which send key release events. This should be fixed in v1.2.2.
