### ISSUE TITLE
Virus message in v1.2.1

### ISSUE THREAD

**Issue by DZZc0rd** [max-niederman/ttyper#86]
Hi, I tried to download ttyper v1.2.1, but got a message with text "Virus detected"

OS: Windows 11
Antivirus: Windows Defender

**Comment by max-niederman** [comment]
Can you give some more context? What OS are you on? Do you have any antivirus software? Did you get the message when you tried to run the executable or when you tried to download it? If the latter, what browser are you on?

**Comment by DZZc0rd** [comment]
When I tried to download from browser(Opera GX) I got this message

**Comment by max-niederman** [comment]
Does the same message show for earlier versions? Also, does the message appear to be displayed by Opera GX?

**Comment by DZZc0rd** [comment]
Yeah
