### ISSUE TITLE
Error: division by zero

### ISSUE THREAD

**Issue by KorigamiK** [max-niederman/ttyper#91]
```bash
hotel year she ntact first search world so data you no good ove ... 
thread 'main' panicked at 'attempt to dmik/.cargo/registry/src/github.com-1ecc6299db9ec823/tui:480:22

│note: run with `RUST_BACKTRACE=1` environment variablee
```

On finishing a test with only two words typed one incorrect.
I can investigate this issue and get back with a pr soon.

**Comment by max-niederman** [comment]
There's already some work on this in #42, so I'm closing this as a duplicate. A PR would be awesome!
